# Generated by Django 5.1.7 on 2025-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id_empresas",
                    models.AutoField(
                        db_column="ID_Empresas", primary_key=True, serialize=False
                    ),
                ),
                (
                    "razaosocial",
                    models.CharField(db_column="RazaoSocial", max_length=255),
                ),
                (
                    "nomefantasia",
                    models.CharField(
                        blank=True, db_column="NomeFantasia", max_length=255, null=True
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, db_column="CNPJ", max_length=50, null=True
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, db_column="Endereco", max_length=255, null=True
                    ),
                ),
                (
                    "endnumero",
                    models.CharField(
                        blank=True, db_column="EndNumero", max_length=50, null=True
                    ),
                ),
                (
                    "endbairro",
                    models.CharField(
                        blank=True, db_column="EndBairro", max_length=255, null=True
                    ),
                ),
                (
                    "endcomplemento",
                    models.CharField(
                        blank=True,
                        db_column="EndComplemento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "endcep",
                    models.CharField(
                        blank=True, db_column="EndCEP", max_length=20, null=True
                    ),
                ),
                (
                    "endcidade",
                    models.CharField(
                        blank=True, db_column="EndCidade", max_length=255, null=True
                    ),
                ),
                (
                    "endestado",
                    models.CharField(
                        blank=True, db_column="EndEstado", max_length=255, null=True
                    ),
                ),
                (
                    "endpais",
                    models.CharField(
                        blank=True, db_column="EndPais", max_length=255, null=True
                    ),
                ),
                (
                    "emptel1",
                    models.CharField(
                        blank=True, db_column="EmpTel1", max_length=50, null=True
                    ),
                ),
                (
                    "emptel2",
                    models.CharField(
                        blank=True, db_column="EmpTel2", max_length=50, null=True
                    ),
                ),
                (
                    "empemail",
                    models.EmailField(
                        blank=True, db_column="EmpEmail", max_length=254, null=True
                    ),
                ),
                (
                    "paginaweb",
                    models.URLField(blank=True, db_column="PaginaWeb", null=True),
                ),
                (
                    "ie",
                    models.CharField(
                        blank=True, db_column="IE", max_length=50, null=True
                    ),
                ),
                (
                    "im",
                    models.CharField(
                        blank=True, db_column="IM", max_length=50, null=True
                    ),
                ),
                (
                    "naturezajuridica",
                    models.CharField(
                        blank=True,
                        db_column="NaturezaJuridica",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "empinicioatividade",
                    models.DateTimeField(
                        blank=True, db_column="EmpInicioAtividade", null=True
                    ),
                ),
                (
                    "empcriado",
                    models.DateTimeField(blank=True, db_column="EmpCriado", null=True),
                ),
                (
                    "dataprotredesim",
                    models.DateTimeField(
                        blank=True, db_column="DataProtREDESIM", null=True
                    ),
                ),
                (
                    "dataprotjuntacomercial",
                    models.DateTimeField(
                        blank=True, db_column="DataProtJuntaComercial", null=True
                    ),
                ),
                (
                    "datapedidoie",
                    models.DateTimeField(
                        blank=True, db_column="DataPedidoIE", null=True
                    ),
                ),
                (
                    "dataregistroalt",
                    models.DateTimeField(
                        blank=True, db_column="DataRegistroAlt", null=True
                    ),
                ),
                (
                    "datamotivo",
                    models.DateTimeField(blank=True, db_column="DataMotivo", null=True),
                ),
                (
                    "ieinicioatividade",
                    models.DateTimeField(
                        blank=True, db_column="IEInicioAtividade", null=True
                    ),
                ),
                (
                    "ievencpedido",
                    models.DateTimeField(
                        blank=True, db_column="IEVencPedido", null=True
                    ),
                ),
                (
                    "datasimples",
                    models.DateTimeField(
                        blank=True, db_column="DataSimples", null=True
                    ),
                ),
                (
                    "dataultdefsimples",
                    models.DateTimeField(
                        blank=True, db_column="DataUltdefSimples", null=True
                    ),
                ),
                (
                    "dataexcsocial",
                    models.DateTimeField(
                        blank=True, db_column="DataExcSocial", null=True
                    ),
                ),
                (
                    "cnhdataexp",
                    models.DateTimeField(blank=True, db_column="CNHdataexp", null=True),
                ),
                (
                    "respdatanasc",
                    models.DateTimeField(
                        blank=True, db_column="RespDataNasc", null=True
                    ),
                ),
                (
                    "enddata",
                    models.DateTimeField(blank=True, db_column="EndData", null=True),
                ),
                (
                    "procuracaodata",
                    models.DateTimeField(
                        blank=True, db_column="ProcuracaoData", null=True
                    ),
                ),
                (
                    "nireregistrodata",
                    models.DateTimeField(
                        blank=True, db_column="NIRERegistroData", null=True
                    ),
                ),
                (
                    "iedataaltsolicitado",
                    models.DateTimeField(
                        blank=True, db_column="IEDataAltSolicitado", null=True
                    ),
                ),
                (
                    "niredata",
                    models.DateTimeField(blank=True, db_column="NireData", null=True),
                ),
                (
                    "dbedata",
                    models.DateTimeField(blank=True, db_column="DBEData", null=True),
                ),
                (
                    "protjuntafinal",
                    models.DateTimeField(
                        blank=True, db_column="ProtJuntaFinal", null=True
                    ),
                ),
                (
                    "prazosimples",
                    models.DateTimeField(
                        blank=True, db_column="PrazoSimples", null=True
                    ),
                ),
                (
                    "avisardia",
                    models.DateTimeField(blank=True, db_column="AvisarDia", null=True),
                ),
                (
                    "processo",
                    models.CharField(
                        blank=True, db_column="Processo", max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=50, null=True
                    ),
                ),
                (
                    "nire",
                    models.CharField(
                        blank=True, db_column="NIRE", max_length=50, null=True
                    ),
                ),
                (
                    "cnaeprincipal",
                    models.TextField(blank=True, db_column="CNAEPrincipal", null=True),
                ),
                (
                    "cnaesecundario",
                    models.TextField(blank=True, db_column="CNAESecundario", null=True),
                ),
                (
                    "ramodeatividade",
                    models.TextField(
                        blank=True, db_column="RamoDeAtividade", null=True
                    ),
                ),
                (
                    "responsavelcpf",
                    models.CharField(
                        blank=True, db_column="ResponsavelCPF", max_length=50, null=True
                    ),
                ),
                (
                    "responsavelnome",
                    models.CharField(
                        blank=True,
                        db_column="ResponsavelNome",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "protocolojuntacomercial",
                    models.CharField(
                        blank=True,
                        db_column="ProtocoloJuntaComercial",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("geral", models.TextField(blank=True, db_column="Geral", null=True)),
                (
                    "protocoloredesim",
                    models.CharField(
                        blank=True,
                        db_column="ProtocoloREDESIM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nirealt",
                    models.CharField(
                        blank=True, db_column="NireAlt", max_length=50, null=True
                    ),
                ),
                (
                    "juntaobs",
                    models.TextField(blank=True, db_column="JuntaObs", null=True),
                ),
                (
                    "nregistroalt",
                    models.CharField(
                        blank=True, db_column="NRegistroAlt", max_length=50, null=True
                    ),
                ),
                (
                    "nireantigos",
                    models.CharField(
                        blank=True, db_column="NireAntigos", max_length=255, null=True
                    ),
                ),
                (
                    "nalteracao",
                    models.CharField(
                        blank=True, db_column="NAlteracao", max_length=50, null=True
                    ),
                ),
                (
                    "redesimobs",
                    models.TextField(blank=True, db_column="RedeSimObs", null=True),
                ),
                (
                    "estadualobs",
                    models.TextField(blank=True, db_column="EstadualObs", null=True),
                ),
                (
                    "prefeituraobs",
                    models.TextField(blank=True, db_column="PrefeituraObs", null=True),
                ),
                (
                    "codigosimples",
                    models.CharField(
                        blank=True, db_column="CodigoSimples", max_length=50, null=True
                    ),
                ),
                (
                    "cpfresponsavel",
                    models.CharField(
                        blank=True, db_column="CPFResponsavel", max_length=50, null=True
                    ),
                ),
                (
                    "nomeresponsavel",
                    models.CharField(
                        blank=True,
                        db_column="NomeResponsavel",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "arquivocontrato",
                    models.CharField(
                        blank=True,
                        db_column="ArquivoContrato",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "procedimento",
                    models.TextField(blank=True, db_column="Procedimento", null=True),
                ),
                (
                    "regimefederal",
                    models.CharField(
                        blank=True, db_column="RegimeFederal", max_length=255, null=True
                    ),
                ),
                (
                    "portedaempresa",
                    models.CharField(
                        blank=True, db_column="PorteDaEmpresa", max_length=50, null=True
                    ),
                ),
                (
                    "tipodeempresa",
                    models.CharField(
                        blank=True, db_column="TipoDeEmpresa", max_length=50, null=True
                    ),
                ),
                (
                    "altconsolidada",
                    models.CharField(
                        blank=True, db_column="AltConsolidada", max_length=50, null=True
                    ),
                ),
                ("motivo", models.TextField(blank=True, db_column="Motivo", null=True)),
                (
                    "iecomprovante",
                    models.CharField(
                        blank=True, db_column="IEComprovante", max_length=255, null=True
                    ),
                ),
                (
                    "bombeirojunta",
                    models.CharField(
                        blank=True, db_column="BombeiroJunta", max_length=50, null=True
                    ),
                ),
                (
                    "iejunta",
                    models.CharField(
                        blank=True, db_column="IEjunta", max_length=50, null=True
                    ),
                ),
                (
                    "tituloeleitor",
                    models.CharField(
                        blank=True, db_column="Tituloeleitor", max_length=50, null=True
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, db_column="area", max_length=50, null=True
                    ),
                ),
                (
                    "area2",
                    models.CharField(
                        blank=True, db_column="area2", max_length=50, null=True
                    ),
                ),
                (
                    "obssimples",
                    models.TextField(blank=True, db_column="ObsSimples", null=True),
                ),
                (
                    "orgaopedsimples",
                    models.CharField(
                        blank=True,
                        db_column="OrgãoPedSimples",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pastadocumentos",
                    models.CharField(
                        blank=True,
                        db_column="PastaDocumentos",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "resprg",
                    models.CharField(
                        blank=True, db_column="RespRG", max_length=50, null=True
                    ),
                ),
                (
                    "historico",
                    models.TextField(blank=True, db_column="Historico", null=True),
                ),
                (
                    "altprot",
                    models.CharField(
                        blank=True, db_column="AltProt", max_length=255, null=True
                    ),
                ),
                (
                    "capitals",
                    models.CharField(
                        blank=True, db_column="CapitalS", max_length=50, null=True
                    ),
                ),
                (
                    "capitali",
                    models.CharField(
                        blank=True, db_column="CapitalI", max_length=50, null=True
                    ),
                ),
                (
                    "cnhnumero",
                    models.CharField(
                        blank=True, db_column="CNHnumero", max_length=50, null=True
                    ),
                ),
                (
                    "cnhexp",
                    models.CharField(
                        blank=True, db_column="CNHexp", max_length=50, null=True
                    ),
                ),
                (
                    "respmae",
                    models.CharField(
                        blank=True, db_column="RespMae", max_length=255, null=True
                    ),
                ),
                (
                    "cadimob",
                    models.CharField(
                        blank=True, db_column="CadImob", max_length=50, null=True
                    ),
                ),
                (
                    "endzona",
                    models.CharField(
                        blank=True, db_column="EndZona", max_length=50, null=True
                    ),
                ),
                (
                    "endquadra",
                    models.CharField(
                        blank=True, db_column="EndQuadra", max_length=50, null=True
                    ),
                ),
                (
                    "resprgsigla",
                    models.CharField(
                        blank=True, db_column="RespRgSigla", max_length=10, null=True
                    ),
                ),
                (
                    "procuracao",
                    models.CharField(
                        blank=True, db_column="Procuracao", max_length=50, null=True
                    ),
                ),
                (
                    "procuracaon",
                    models.CharField(
                        blank=True, db_column="ProcuracaoN", max_length=50, null=True
                    ),
                ),
                (
                    "novarazaosocial1",
                    models.CharField(
                        blank=True,
                        db_column="NovaRazaoSocial1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "novarazaosocial2",
                    models.CharField(
                        blank=True,
                        db_column="NovaRazaoSocial2",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "novarazaosocial3",
                    models.CharField(
                        blank=True,
                        db_column="NovaRazaoSocial3",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "novarazaosocial",
                    models.CharField(
                        blank=True,
                        db_column="NovaRazaoSocial",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "eventos",
                    models.TextField(blank=True, db_column="Eventos", null=True),
                ),
                (
                    "senhagov",
                    models.CharField(
                        blank=True, db_column="SenhaGov", max_length=255, null=True
                    ),
                ),
                (
                    "resppai",
                    models.CharField(
                        blank=True, db_column="RespPai", max_length=255, null=True
                    ),
                ),
                (
                    "nireregistro",
                    models.CharField(
                        blank=True, db_column="NIRERegistro", max_length=50, null=True
                    ),
                ),
                (
                    "novarazaosocialfinal",
                    models.CharField(
                        blank=True,
                        db_column="NovaRazaoSocialFinal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ieonline",
                    models.CharField(
                        blank=True, db_column="IEOnline", max_length=50, null=True
                    ),
                ),
                (
                    "ietipo",
                    models.CharField(
                        blank=True, db_column="IETipo", max_length=50, null=True
                    ),
                ),
                (
                    "ieeprocnum",
                    models.CharField(
                        blank=True, db_column="IEeProcNum", max_length=255, null=True
                    ),
                ),
                (
                    "sistemaexterno",
                    models.CharField(
                        blank=True,
                        db_column="SistemaExterno",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dadossocios",
                    models.TextField(blank=True, db_column="DadosSocios", null=True),
                ),
                (
                    "quantidadesocios",
                    models.CharField(
                        blank=True,
                        db_column="QuantidadeSocios",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "razaosocialantiga",
                    models.CharField(
                        blank=True,
                        db_column="RazaoSocialAntiga",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "situacaocadastral",
                    models.CharField(
                        blank=True,
                        db_column="SituacaoCadastral",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "divisaocapitalsocios",
                    models.CharField(
                        blank=True,
                        db_column="DivisaoCapitalSocios",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "capitalquotavalor",
                    models.CharField(
                        blank=True,
                        db_column="CapitalQuotaValor",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "capitaquotatotal",
                    models.CharField(
                        blank=True,
                        db_column="CapitaQuotaTotal",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cpfdoconjuge",
                    models.CharField(
                        blank=True, db_column="CPFdoCONJUGE", max_length=50, null=True
                    ),
                ),
                (
                    "nomedoconjuge",
                    models.CharField(
                        blank=True, db_column="NOMEdoCONJUGE", max_length=255, null=True
                    ),
                ),
                (
                    "responsavelorgaorg",
                    models.CharField(
                        blank=True,
                        db_column="ResponsavelOrgaoRG",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "responsavelestadoorgaorg",
                    models.CharField(
                        blank=True,
                        db_column="ResponsavelEstadoOrgaoRG",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "numeroprocesso",
                    models.CharField(
                        blank=True,
                        db_column="NumeroProcesso",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reciboprocesso",
                    models.CharField(
                        blank=True,
                        db_column="ReciboProcesso",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sede",
                    models.CharField(
                        blank=True, db_column="SEDE", max_length=50, null=True
                    ),
                ),
                (
                    "pontodereferencia",
                    models.CharField(
                        blank=True,
                        db_column="PontoDeReferencia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tipounidadeprodutiva",
                    models.CharField(
                        blank=True,
                        db_column="TipoUnidadeProdutiva",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "formadeatuacao",
                    models.CharField(
                        blank=True,
                        db_column="FormaDeAtuacao",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dadoscomplestabelecimento",
                    models.TextField(
                        blank=True, db_column="DadosComplEstabelecimento", null=True
                    ),
                ),
                (
                    "dadoscomplatividade",
                    models.TextField(
                        blank=True, db_column="DadosComplAtividade", null=True
                    ),
                ),
                (
                    "dadoscomplpavimentos",
                    models.CharField(
                        blank=True,
                        db_column="DadosComplPavimentos",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dadoscomplpessoas",
                    models.CharField(
                        blank=True,
                        db_column="DadosComplPessoas",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dadoscomplsubsolo",
                    models.CharField(
                        blank=True,
                        db_column="DadosComplSubsolo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dadoscomplliquido",
                    models.CharField(
                        blank=True,
                        db_column="DadosComplLiquido",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dadoscomplglp",
                    models.CharField(
                        blank=True, db_column="DadosComplGLP", max_length=50, null=True
                    ),
                ),
                (
                    "ajudatipodeunidade",
                    models.TextField(
                        blank=True, db_column="AjudaTipodeUnidade", null=True
                    ),
                ),
                (
                    "dbeprotocolo",
                    models.CharField(
                        blank=True, db_column="DBEProtocolo", max_length=255, null=True
                    ),
                ),
                (
                    "federalprotocolo",
                    models.CharField(
                        blank=True,
                        db_column="FederalProtocolo",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "senhasdeacesso",
                    models.TextField(blank=True, db_column="SenhasDeAcesso", null=True),
                ),
                (
                    "capitalsocialantigo",
                    models.CharField(
                        blank=True,
                        db_column="CapitalSocialAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "capitalantigomudou",
                    models.CharField(
                        blank=True,
                        db_column="CapitalAntigoMudou",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cnaeatividadenolocal",
                    models.TextField(
                        blank=True, db_column="CNAEAtividadeNoLocal", null=True
                    ),
                ),
                (
                    "cnaeatvlocalprincipal",
                    models.TextField(
                        blank=True, db_column="CNAEAtvLocalPrincipal", null=True
                    ),
                ),
                (
                    "cnaeatvlocalsecundarios",
                    models.TextField(
                        blank=True, db_column="CNAEAtvLocalSEcundarios", null=True
                    ),
                ),
                (
                    "bombeiroatvadm",
                    models.CharField(
                        blank=True, db_column="BombeiroAtvAdm", max_length=50, null=True
                    ),
                ),
                (
                    "bombeiroatvresidencia",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroAtvresidencia",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cnaedescricaooficial",
                    models.TextField(
                        blank=True, db_column="CNAEdescricaoOficial", null=True
                    ),
                ),
                (
                    "objetodoestabelecimento",
                    models.TextField(
                        blank=True, db_column="ObjetoDOEstabelecimento", null=True
                    ),
                ),
                (
                    "simplesecac",
                    models.CharField(
                        blank=True, db_column="SimplesEcac", max_length=50, null=True
                    ),
                ),
                (
                    "avisarempresatexto",
                    models.TextField(
                        blank=True, db_column="AvisarEmpresaTexto", null=True
                    ),
                ),
                (
                    "temenderecoantigoemp",
                    models.CharField(
                        blank=True,
                        db_column="TemEnderecoAntigoEmp",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "enderecoantigoemp",
                    models.CharField(
                        blank=True,
                        db_column="EnderecoAntigoEmp",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "codsistemaexterno",
                    models.CharField(
                        blank=True,
                        db_column="CodSistemaExterno",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "avisarempresa",
                    models.TextField(blank=True, db_column="AvisarEmpresa", null=True),
                ),
                (
                    "prioridade",
                    models.CharField(
                        blank=True, db_column="Prioridade", max_length=20, null=True
                    ),
                ),
                (
                    "lembrete",
                    models.CharField(
                        blank=True, db_column="Lembrete", max_length=20, null=True
                    ),
                ),
                (
                    "doccontratos",
                    models.BinaryField(blank=True, db_column="DocContratos", null=True),
                ),
            ],
            options={
                "db_table": "Empresas",
                "managed": True,
            },
        ),
    ]
