# Generated by Django 5.1.7 on 2025-05-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="enddata",
            field=models.CharField(
                blank=True, db_column="EndData", max_length=50, null=True
            ),
        ),
    ]
