# Generated by Django 5.2.2 on 2025-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_enddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="enderecoantigoemp",
            field=models.TextField(
                blank=True, db_column="EnderecoAntigoEmp", null=True
            ),
        ),
    ]
