# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_enderecoantigoemp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': True, 'ordering': ['razaosocial']},
        ),
    ]
