# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NaturezaJuridica",
            fields=[
                (
                    "id_natureza_juridica",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "db_table": "Naturezajuridica",
            },
        ),
    ]
