# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturezaJuridica', '0002_alter_naturezajuridica_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naturezajuridica',
            options={'managed': False, 'ordering': ['ID_Naturezajuridica']},
        ),
    ]
