# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secao", models.CharField(max_length=100)),
                ("divisao", models.CharField(max_length=100)),
                ("grupo", models.CharField(max_length=100)),
                ("classe", models.CharField(max_length=100)),
                ("subclasse", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
            options={
                "db_table": "CNAESubclasses23",
            },
        ),
    ]
