# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNAE', '0002_alter_cnae_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cnae',
            options={'managed': False, 'ordering': ['secao', 'divisao', 'grupo', 'classe', 'subclasse']},
        ),
    ]
