# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrasilEstados",
            fields=[
                ("codigo_uf", models.IntegerField(primary_key=True, serialize=False)),
                ("uf", models.CharField(max_length=2)),
                ("nome", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("regiao", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "BrasilEstado",
            },
        ),
    ]
