# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventosEmpresa",
            fields=[
                (
                    "id_eventos_empresa",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("eventos", models.CharField(max_length=255)),
                ("empresa_facil", models.BooleanField(default=False)),
                ("receita_federal", models.BooleanField(default=False)),
                ("receita_estadual", models.BooleanField(default=False)),
                ("prefeitura_municipal", models.BooleanField(default=False)),
                ("eventos_descricao_titulo", models.CharField(max_length=255)),
                ("eventos_descricao", models.TextField()),
            ],
            options={
                "db_table": "EventosEmpresa",
            },
        ),
    ]
