# Generated by Django 5.1.7 on 2025-04-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventosEmpresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventosempresa",
            options={"managed": False},
        ),
    ]
