# Generated by Django 5.2.1 on 2025-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CADSituacaoAlvara", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CADSituacaoAlvara",
            fields=[
                (
                    "ID_CADSituacaoAlv",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Situação do Alvará",
                "verbose_name_plural": "Situações dos Alvarás",
                "db_table": "CADSituacaoAlvara",
                "managed": False,
            },
        ),
    ]
