# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CADSituacaoAlvara', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadsituacaoalvara',
            options={'managed': False, 'ordering': ['ID_CADSituacaoAlv'], 'verbose_name': 'Situação do Alvará', 'verbose_name_plural': 'Situações dos Alvarás'},
        ),
    ]
