# Generated by Django 5.1.7 on 2025-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id_socios",
                    models.AutoField(
                        db_column="ID_Socios", primary_key=True, serialize=False
                    ),
                ),
                ("cpf", models.CharField(db_column="CPF", max_length=50)),
                (
                    "nomecompleto",
                    models.CharField(db_column="NomeCompleto", max_length=255),
                ),
                (
                    "nomemae",
                    models.CharField(
                        blank=True, db_column="NomeMae", max_length=255, null=True
                    ),
                ),
                (
                    "nomepai",
                    models.CharField(
                        blank=True, db_column="NomePai", max_length=255, null=True
                    ),
                ),
                (
                    "datadenasc",
                    models.CharField(
                        blank=True, db_column="DatadeNasc", max_length=50, null=True
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, db_column="RG", max_length=50, null=True
                    ),
                ),
                (
                    "orgaorg",
                    models.CharField(
                        blank=True, db_column="OrgaoRG", max_length=50, null=True
                    ),
                ),
                (
                    "estadorg",
                    models.CharField(
                        blank=True, db_column="EstadoRG", max_length=50, null=True
                    ),
                ),
                (
                    "titulodeeleitor",
                    models.CharField(
                        blank=True,
                        db_column="TituloDeEleitor",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "senhagov",
                    models.CharField(
                        blank=True, db_column="SenhaGov", max_length=50, null=True
                    ),
                ),
                (
                    "cnh",
                    models.CharField(
                        blank=True, db_column="CNH", max_length=50, null=True
                    ),
                ),
                (
                    "cnhexpedicao",
                    models.CharField(
                        blank=True, db_column="CNHExpedicao", max_length=50, null=True
                    ),
                ),
                (
                    "cnhdataexp",
                    models.CharField(
                        blank=True, db_column="CNHDataExp", max_length=50, null=True
                    ),
                ),
                (
                    "civil",
                    models.CharField(
                        blank=True, db_column="Civil", max_length=50, null=True
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, db_column="CEP", max_length=20, null=True
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, db_column="RUA", max_length=255, null=True
                    ),
                ),
                (
                    "num",
                    models.CharField(
                        blank=True, db_column="Num", max_length=50, null=True
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, db_column="Bairro", max_length=100, null=True
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, db_column="Complemento", max_length=255, null=True
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, db_column="Cidade", max_length=100, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, db_column="Estado", max_length=100, null=True
                    ),
                ),
                (
                    "país",
                    models.CharField(
                        blank=True, db_column="País", max_length=100, null=True
                    ),
                ),
                (
                    "telefone1",
                    models.CharField(
                        blank=True, db_column="Telefone1", max_length=50, null=True
                    ),
                ),
                (
                    "telefone2",
                    models.CharField(
                        blank=True, db_column="Telefone2", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_column="eMail", max_length=254, null=True
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, db_column="Genero", max_length=20, null=True
                    ),
                ),
                (
                    "cpfdoconjuge",
                    models.CharField(
                        blank=True, db_column="CPFdoCONJUGE", max_length=50, null=True
                    ),
                ),
                (
                    "nomedoconjuge",
                    models.CharField(
                        blank=True, db_column="NOMEdoCONJUGE", max_length=255, null=True
                    ),
                ),
                (
                    "profissao",
                    models.CharField(
                        blank=True, db_column="Profissão", max_length=100, null=True
                    ),
                ),
                (
                    "outrosdados",
                    models.TextField(blank=True, db_column="OutrosDados", null=True),
                ),
                (
                    "menoridade",
                    models.CharField(
                        blank=True, db_column="MenorIdade", max_length=50, null=True
                    ),
                ),
                (
                    "registroorgao",
                    models.CharField(
                        blank=True, db_column="RegistroOrgao", max_length=50, null=True
                    ),
                ),
                (
                    "registroestado",
                    models.CharField(
                        blank=True, db_column="RegistroEstado", max_length=50, null=True
                    ),
                ),
                (
                    "registronumero",
                    models.CharField(
                        blank=True, db_column="RegistroNumero", max_length=50, null=True
                    ),
                ),
                (
                    "registrodata",
                    models.CharField(
                        blank=True, db_column="RegistroData", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Socios",
                "managed": False,
            },
        ),
    ]
