# Generated by Django 5.1.7 on 2025-04-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socio",
            options={"managed": True},
        ),
    ]
