# Generated by Django 5.1.7 on 2025-04-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0002_alter_socio_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socio",
            options={"managed": False},
        ),
    ]
