# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'managed': False, 'ordering': ['nomecompleto']},
        ),
    ]
