# Generated by Django 5.1.7 on 2025-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=150, unique=True)),
                ("senha", models.CharField(max_length=128)),
                (
                    "nome_completo",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "db_table": "Login",
            },
        ),
    ]
