# Generated by Django 5.1.7 on 2025-03-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="login",
            options={"managed": False},
        ),
    ]
