# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_login_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False, 'ordering': ['usuario']},
        ),
    ]
