# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrasilDistritos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_municipio", models.IntegerField()),
                ("id_microrregiao", models.IntegerField()),
                ("id_mesorregiao", models.IntegerField()),
                ("id_estado", models.IntegerField()),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "BrasilDistritos",
            },
        ),
    ]
