# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrasilDistritos', '0002_alter_brasildistritos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brasildistritos',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
