# Generated by Django 5.1.7 on 2025-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contador",
            fields=[
                (
                    "ID_Contador",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("Nome", models.CharField(max_length=255)),
                ("CPF", models.CharField(max_length=20)),
                ("CRC", models.CharField(max_length=50)),
                ("ExpedicaoCRC", models.CharField(max_length=50)),
                ("RG", models.CharField(max_length=50)),
                ("RazaoSocial", models.TextField()),
                ("CNPJ", models.CharField(max_length=20)),
                ("Telefone", models.CharField(max_length=20)),
                ("email", models.TextField()),
                ("CMC", models.CharField(max_length=50)),
                ("Endereco", models.TextField()),
                ("EndNum", models.CharField(max_length=20)),
                ("EndComp", models.TextField()),
                ("EndBairro", models.TextField()),
                ("EndCidade", models.CharField(max_length=100)),
                ("EndEstado", models.CharField(max_length=50)),
                ("EndCEP", models.CharField(max_length=20)),
                ("RGSigla", models.CharField(max_length=10)),
                ("EstadoCivil", models.TextField()),
                ("EstadoCivilDesc", models.TextField()),
                ("DataNasc", models.CharField(max_length=20)),
                ("Genero", models.TextField()),
                ("Profissao", models.TextField()),
                ("NomePai", models.TextField()),
                ("NomeMae", models.TextField()),
                ("email1", models.TextField()),
                ("email2", models.TextField()),
                ("Anotacoes", models.TextField()),
                ("IEescritorio", models.TextField()),
            ],
            options={
                "db_table": '"Contador"',
            },
        ),
    ]
