# Generated by Django 5.1.7 on 2025-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contadores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contador",
            name="CMC",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="CNPJ",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="CRC",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndBairro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndCidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndComp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndNum",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="Endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="ExpedicaoCRC",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="ID_Contador",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contador",
            name="RG",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="RazaoSocial",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="Telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="email1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="email2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
