# Generated by Django 5.1.7 on 2025-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contadores", "0002_alter_contador_cmc_alter_contador_cnpj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contador",
            name="Anotacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="CPF",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="DataNasc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndCEP",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EndEstado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EstadoCivil",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="EstadoCivilDesc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="Genero",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="IEescritorio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="Nome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="NomeMae",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="NomePai",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="Profissao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contador",
            name="RGSigla",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
