# Generated by Django 5.2.1 on 2025-05-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contadores", "0003_alter_contador_anotacoes_alter_contador_cpf_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contador",
            options={"managed": False},
        ),
    ]
