# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contadores', '0004_alter_contador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contador',
            options={'managed': False, 'ordering': ['ID_Contador']},
        ),
    ]
