# Generated by Django 5.1.7 on 2025-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcelamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(db_column="RazaoSocial", max_length=255),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, db_column="CNPJ", max_length=50, null=True
                    ),
                ),
                (
                    "forma_envio",
                    models.CharField(
                        blank=True, db_column="FormaDeEnvio", max_length=50, null=True
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, db_column="Responsavel", max_length=255, null=True
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, db_column="Whatsapp", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=255, null=True
                    ),
                ),
                (
                    "socio",
                    models.CharField(
                        blank=True, db_column="Socio", max_length=255, null=True
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_column="CPF", max_length=50, null=True
                    ),
                ),
                (
                    "senhagov",
                    models.CharField(
                        blank=True, db_column="SenhaGov", max_length=50, null=True
                    ),
                ),
                (
                    "data_criacao",
                    models.CharField(
                        blank=True, db_column="DataCriacao", max_length=50, null=True
                    ),
                ),
                (
                    "data_lembrete",
                    models.CharField(
                        blank=True, db_column="DataLembrete", max_length=50, null=True
                    ),
                ),
                (
                    "data_finalizado",
                    models.CharField(
                        blank=True, db_column="DataFinalizado", max_length=50, null=True
                    ),
                ),
                (
                    "mei",
                    models.CharField(
                        blank=True, db_column="MEI", max_length=50, null=True
                    ),
                ),
                (
                    "inss_antigo",
                    models.CharField(
                        blank=True, db_column="InssAntigo", max_length=50, null=True
                    ),
                ),
                (
                    "inss_novo",
                    models.CharField(
                        blank=True, db_column="InssNovo", max_length=50, null=True
                    ),
                ),
                (
                    "inss_procur",
                    models.CharField(
                        blank=True, db_column="InssProcur", max_length=50, null=True
                    ),
                ),
                (
                    "data_solic_mei",
                    models.CharField(
                        blank=True, db_column="DataSolicMEI", max_length=50, null=True
                    ),
                ),
                (
                    "data_envia_mei",
                    models.CharField(
                        blank=True, db_column="DataEnviaMEI", max_length=50, null=True
                    ),
                ),
                (
                    "data_final_mei",
                    models.CharField(
                        blank=True, db_column="DataFinalMEI", max_length=50, null=True
                    ),
                ),
                (
                    "motivo_mei",
                    models.CharField(
                        blank=True, db_column="MotivoMEI", max_length=255, null=True
                    ),
                ),
                (
                    "prot_mei",
                    models.CharField(
                        blank=True, db_column="ProtMEI", max_length=50, null=True
                    ),
                ),
                (
                    "total_parc_mei",
                    models.CharField(
                        blank=True, db_column="TotalParcMEI", max_length=50, null=True
                    ),
                ),
                (
                    "envia_parc_mei",
                    models.CharField(
                        blank=True, db_column="EnviaParcMEI", max_length=50, null=True
                    ),
                ),
                (
                    "data_solic_antigo",
                    models.CharField(
                        blank=True,
                        db_column="DataSolicAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "data_envia_antigo",
                    models.CharField(
                        blank=True,
                        db_column="DataEnviaAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "data_final_antigo",
                    models.CharField(
                        blank=True,
                        db_column="DataFinalAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "motivo_antigo",
                    models.CharField(
                        blank=True, db_column="MotivoAntigo", max_length=255, null=True
                    ),
                ),
                (
                    "prot_antigo",
                    models.CharField(
                        blank=True, db_column="ProtAntigo", max_length=50, null=True
                    ),
                ),
                (
                    "total_parc_antigo",
                    models.CharField(
                        blank=True,
                        db_column="TotalParcAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "envia_parc_antigo",
                    models.CharField(
                        blank=True,
                        db_column="EnviaParcAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "data_solic_novo",
                    models.CharField(
                        blank=True, db_column="DataSolicNovo", max_length=50, null=True
                    ),
                ),
                (
                    "data_envio_novo",
                    models.CharField(
                        blank=True, db_column="DataEnvioNovo", max_length=50, null=True
                    ),
                ),
                (
                    "data_final_novo",
                    models.CharField(
                        blank=True, db_column="DataFinalNovo", max_length=50, null=True
                    ),
                ),
                (
                    "motivo_novo",
                    models.CharField(
                        blank=True, db_column="MotivoNovo", max_length=255, null=True
                    ),
                ),
                (
                    "prot_novo",
                    models.CharField(
                        blank=True, db_column="ProtNovo", max_length=50, null=True
                    ),
                ),
                (
                    "total_parc_novo",
                    models.CharField(
                        blank=True, db_column="TotalParcNovo", max_length=50, null=True
                    ),
                ),
                (
                    "envia_parc_novo",
                    models.CharField(
                        blank=True, db_column="EnviaParcNovo", max_length=50, null=True
                    ),
                ),
                (
                    "data_solic_proc",
                    models.CharField(
                        blank=True, db_column="DataSolicProc", max_length=50, null=True
                    ),
                ),
                (
                    "data_envia_proc",
                    models.CharField(
                        blank=True, db_column="DataEnviaProc", max_length=50, null=True
                    ),
                ),
                (
                    "data_final_proc",
                    models.CharField(
                        blank=True, db_column="DataFinalProc", max_length=50, null=True
                    ),
                ),
                (
                    "motivo_proc",
                    models.CharField(
                        blank=True, db_column="MotivoProc", max_length=255, null=True
                    ),
                ),
                (
                    "prot_proc",
                    models.CharField(
                        blank=True, db_column="Protproc", max_length=50, null=True
                    ),
                ),
                (
                    "total_parc_proc",
                    models.CharField(
                        blank=True, db_column="TotalParcProc", max_length=50, null=True
                    ),
                ),
                (
                    "envia_parc_proc",
                    models.CharField(
                        blank=True, db_column="EnviaParcProc", max_length=50, null=True
                    ),
                ),
                (
                    "id_parcel",
                    models.CharField(
                        blank=True, db_column="ID_Parcel", max_length=50, null=True
                    ),
                ),
                (
                    "parcel_env_mei",
                    models.CharField(
                        blank=True, db_column="ParcelEnvMEI", max_length=50, null=True
                    ),
                ),
                (
                    "parcel_env_inss_ant",
                    models.CharField(
                        blank=True,
                        db_column="ParcelEnvINSSAnt",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parcel_env_inss_nov",
                    models.CharField(
                        blank=True,
                        db_column="ParcelEnvINSSNov",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parcel_env_inss_proc",
                    models.CharField(
                        blank=True,
                        db_column="ParcelEnvINSSProc",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "finalizado_empresa",
                    models.CharField(
                        blank=True,
                        db_column="FinalizadoEmpresa",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "finalizado_mei",
                    models.CharField(
                        blank=True, db_column="FinalizadoMEI", max_length=50, null=True
                    ),
                ),
                (
                    "finalizado_inss_ant",
                    models.CharField(
                        blank=True,
                        db_column="FinalizadoINSSAnt",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "finalizado_inss_nov",
                    models.CharField(
                        blank=True,
                        db_column="FinalizadoINSSNov",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "finalizado_inss_proc",
                    models.CharField(
                        blank=True,
                        db_column="FinalizadoINSSProc",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "finalizado_mes_geral",
                    models.CharField(
                        blank=True,
                        db_column="FinalizadoMesGeral",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "geral",
                    models.CharField(
                        blank=True, db_column="Geral", max_length=50, null=True
                    ),
                ),
                (
                    "para_fazer",
                    models.CharField(
                        blank=True, db_column="ParaFazer", max_length=255, null=True
                    ),
                ),
                (
                    "atraso_parcela_mei",
                    models.CharField(
                        blank=True,
                        db_column="AtrasoParcelaMEI",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "atraso_parcela_inss_antigo",
                    models.CharField(
                        blank=True,
                        db_column="AtrasoParcelaINSSAntigo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "atraso_parcela_inss_novo",
                    models.CharField(
                        blank=True,
                        db_column="AtrasoParcelaINSSNovo",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "atraso_parcela_inss_procu",
                    models.CharField(
                        blank=True,
                        db_column="AtrasoParcelaINSSProcu",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Parcelamentos",
                "managed": False,
            },
        ),
    ]
