# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamentos', '0003_alter_parcelamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelamento',
            options={'managed': False, 'ordering': ['id_parcel']},
        ),
    ]
