# Generated by Django 5.2.2 on 2025-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BombeiroCNAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ocupacao", models.TextField(db_column="Ocupacao")),
                ("Descricao", models.TextField(db_column="Descricao")),
                ("Divisao", models.TextField(db_column="Divisao")),
                ("CNAE", models.TextField(db_column="CNAE")),
                ("Carga_de_incendio", models.TextField(db_column="Carga_de_incendio")),
            ],
            options={
                "db_table": "BombeiroCNAE",
                "managed": False,
            },
        ),
    ]
