# Generated by Django 5.2.2 on 2025-07-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bombeirosCNAE", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bombeirocnae",
            table="bombeirocnae",
        ),
    ]
