# Generated by Django 5.1.7 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CADstatus",
            fields=[
                ("ID_CADstatus", models.AutoField(primary_key=True, serialize=False)),
                ("Descricao", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "CADstatus",
            },
        ),
    ]
