# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadstatus',
            options={'ordering': ['ID_CADstatus']},
        ),
    ]
