# Generated by Django 5.2.1 on 2025-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anotacoes",
            fields=[
                ("ID_Anotacoes", models.AutoField(primary_key=True, serialize=False)),
                ("Usuario", models.CharField(blank=True, max_length=255, null=True)),
                ("Federal", models.TextField(blank=True, null=True)),
                ("Estadual", models.TextField(blank=True, null=True)),
                ("Municipal", models.TextField(blank=True, null=True)),
                ("Inicial", models.TextField(blank=True, null=True)),
                ("Demais", models.TextField(blank=True, null=True)),
                ("Legalizacao", models.TextField(blank=True, null=True)),
                ("Anexos", models.TextField(blank=True, null=True)),
                ("Anexo1", models.TextField(blank=True, null=True)),
                ("Anexo2", models.TextField(blank=True, null=True)),
                ("Anexo3", models.TextField(blank=True, null=True)),
                ("Anexo4", models.TextField(blank=True, null=True)),
                ("Anexo5", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Anotação",
                "verbose_name_plural": "Anotações",
                "db_table": "Anotacoes",
                "managed": False,
            },
        ),
    ]
