# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacoes',
            options={'managed': False, 'ordering': ['ID_Anotacoes'], 'verbose_name': 'Anotação', 'verbose_name_plural': 'Anotações'},
        ),
    ]
