# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrasilMunicipios",
            fields=[
                ("codigo_ibge", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("capital", models.BooleanField(default=False)),
                ("codigo_uf", models.IntegerField()),
                ("siafi_id", models.CharField(max_length=10)),
                ("ddd", models.CharField(max_length=2)),
                ("fuso_horario", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "BrasilMunicipios",
            },
        ),
    ]
