# Generated by Django 5.1.7 on 2025-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sites",
            fields=[
                ("id_sites", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("site_estado", models.URLField(blank=True, max_length=500, null=True)),
                ("site_cidade", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "site_junta_unificada",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_junta_antiga",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_alvara1",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_alvara2",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("distrito", models.CharField(blank=True, max_length=100, null=True)),
                ("estado_sigla", models.CharField(max_length=2)),
                (
                    "site_alvara_pedido1",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_alvara_pedido2",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_pref_protocolo",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "site_redesim_protocolo",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_redesim_consulta_cnpj",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_redesim_abrir_cnpj",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "site_redesim_meu_cnpj",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "bombeiro_consulta",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "bombeiro_solicita",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "bombeiro_unificado",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "bombeiro_redesim",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "federal_ecac",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "federal_parc_proc",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "federal_procuradoria",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "Sites",
            },
        ),
    ]
