# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0002_alter_sites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sites',
            options={'managed': False, 'ordering': ['estado', 'cidade']},
        ),
    ]
