# Generated by Django 5.1.7 on 2025-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laudo",
            fields=[
                (
                    "id_laudos",
                    models.AutoField(
                        db_column="ID_Laudos", primary_key=True, serialize=False
                    ),
                ),
                (
                    "razaosocial",
                    models.CharField(db_column="RazaoSocial", max_length=255),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, db_column="CNPJ", max_length=50, null=True
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, db_column="Endereco", max_length=255, null=True
                    ),
                ),
                (
                    "endnum",
                    models.CharField(
                        blank=True, db_column="EndNum", max_length=50, null=True
                    ),
                ),
                (
                    "endcomp",
                    models.CharField(
                        blank=True, db_column="EndComp", max_length=255, null=True
                    ),
                ),
                (
                    "enddata",
                    models.CharField(
                        blank=True, db_column="EndData", max_length=50, null=True
                    ),
                ),
                (
                    "endquadra",
                    models.CharField(
                        blank=True, db_column="EndQuadra", max_length=100, null=True
                    ),
                ),
                (
                    "endzona",
                    models.CharField(
                        blank=True, db_column="EndZona", max_length=50, null=True
                    ),
                ),
                (
                    "endcep",
                    models.CharField(
                        blank=True, db_column="EndCEP", max_length=20, null=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, db_column="Telefone", max_length=50, null=True
                    ),
                ),
                (
                    "cnae",
                    models.CharField(
                        blank=True, db_column="CNAE", max_length=100, null=True
                    ),
                ),
                (
                    "natureza_pedido",
                    models.CharField(
                        blank=True,
                        db_column="NaturezaDoPedido",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "natureza_pedido_obs",
                    models.CharField(
                        blank=True,
                        db_column="NaturezaDoPedidoOBS",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "requerente",
                    models.CharField(
                        blank=True, db_column="Requerente", max_length=255, null=True
                    ),
                ),
                (
                    "cpf_requerente",
                    models.CharField(
                        blank=True, db_column="CPFRequerente", max_length=50, null=True
                    ),
                ),
                (
                    "end_requerente",
                    models.CharField(
                        blank=True, db_column="EndRequerente", max_length=255, null=True
                    ),
                ),
                (
                    "fone_requerente",
                    models.CharField(
                        blank=True, db_column="FoneRequerente", max_length=50, null=True
                    ),
                ),
                (
                    "email_requerente",
                    models.EmailField(
                        blank=True,
                        db_column="EmailRequerente",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "cnpj_requerente",
                    models.CharField(
                        blank=True, db_column="CNPJRequerente", max_length=50, null=True
                    ),
                ),
                (
                    "rg_requerente",
                    models.CharField(
                        blank=True, db_column="RGRequerente", max_length=50, null=True
                    ),
                ),
                (
                    "ramodeatividade",
                    models.CharField(
                        blank=True,
                        db_column="Ramodeatividade",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("obs", models.TextField(blank=True, db_column="Obs", null=True)),
                (
                    "area",
                    models.CharField(
                        blank=True, db_column="area", max_length=50, null=True
                    ),
                ),
                (
                    "resptecnico",
                    models.CharField(
                        blank=True, db_column="Resptecnico", max_length=255, null=True
                    ),
                ),
                (
                    "resptecnico_numero",
                    models.CharField(
                        blank=True,
                        db_column="ResptecnicoNumero",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lembrete",
                    models.TextField(blank=True, db_column="Lembrete", null=True),
                ),
                (
                    "endbairro",
                    models.CharField(
                        blank=True, db_column="EndBairro", max_length=100, null=True
                    ),
                ),
                (
                    "endcidade",
                    models.CharField(
                        blank=True, db_column="EndCidade", max_length=100, null=True
                    ),
                ),
                (
                    "endestado",
                    models.CharField(
                        blank=True, db_column="EndEstado", max_length=100, null=True
                    ),
                ),
                (
                    "bombeiros",
                    models.CharField(
                        blank=True, db_column="Bombeiros", max_length=100, null=True
                    ),
                ),
                (
                    "bombeiros_situacao",
                    models.CharField(
                        blank=True,
                        db_column="BombeirosSituacao",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bombeiros_venc",
                    models.CharField(
                        blank=True, db_column="BombeirosVenc", max_length=50, null=True
                    ),
                ),
                (
                    "ambiental",
                    models.CharField(
                        blank=True, db_column="Ambiental", max_length=100, null=True
                    ),
                ),
                (
                    "ambiental_situacao",
                    models.CharField(
                        blank=True,
                        db_column="AmbientalSituacao",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ambiental_venc",
                    models.CharField(
                        blank=True, db_column="AmbientalVenc", max_length=50, null=True
                    ),
                ),
                (
                    "viabilidade",
                    models.CharField(
                        blank=True, db_column="Viabilidade", max_length=100, null=True
                    ),
                ),
                (
                    "viabilidade_situacao",
                    models.CharField(
                        blank=True,
                        db_column="ViabilidadeSituacao",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "viabilidade_vec",
                    models.CharField(
                        blank=True, db_column="ViabilidadeVec", max_length=50, null=True
                    ),
                ),
                (
                    "sanitario",
                    models.CharField(
                        blank=True, db_column="Sanitario", max_length=100, null=True
                    ),
                ),
                (
                    "sanitario_situacao",
                    models.CharField(
                        blank=True,
                        db_column="SanitarioSituacao",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sanitario_venc",
                    models.CharField(
                        blank=True, db_column="SanitarioVenc", max_length=50, null=True
                    ),
                ),
                (
                    "setran",
                    models.CharField(
                        blank=True, db_column="Setran", max_length=100, null=True
                    ),
                ),
                (
                    "setran_situacao",
                    models.CharField(
                        blank=True,
                        db_column="SetranSituacao",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "setran_venc",
                    models.CharField(
                        blank=True, db_column="SetranVenc", max_length=50, null=True
                    ),
                ),
                (
                    "bombeiro_exigencia",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroExigencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ambiental_exigencia",
                    models.CharField(
                        blank=True,
                        db_column="AmbientalExigencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "viabilidade_exigencia",
                    models.CharField(
                        blank=True,
                        db_column="ViabilidadeExigencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sanitario_exigencia",
                    models.CharField(
                        blank=True,
                        db_column="SanitarioExigencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "setran_exigencia",
                    models.CharField(
                        blank=True,
                        db_column="SetranExigencia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bombeiro_data_provisorio",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroDataProvisorio",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ambiental_data_provisorio",
                    models.CharField(
                        blank=True,
                        db_column="AmbientalDataProvisorio",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "viabilidade_data_provisorio",
                    models.CharField(
                        blank=True,
                        db_column="ViabilidadeDataProvisorio",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sanitario_data_provisorio",
                    models.CharField(
                        blank=True,
                        db_column="SanitarioDataProvisorio",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "setran_data_provisorio",
                    models.CharField(
                        blank=True,
                        db_column="SetranDataProvisorio",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bombeiro_n_processo",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroNProcesso",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bombeiro_data_ped_processo",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroDataPedProcesso",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nlaudo",
                    models.CharField(
                        blank=True, db_column="Nlaudo", max_length=50, null=True
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True, db_column="Situacao", max_length=50, null=True
                    ),
                ),
                (
                    "data_criado",
                    models.CharField(
                        blank=True, db_column="DataCriado", max_length=50, null=True
                    ),
                ),
                (
                    "data_entrada",
                    models.CharField(
                        blank=True, db_column="DataEntrada", max_length=50, null=True
                    ),
                ),
                (
                    "pendencia",
                    models.CharField(
                        blank=True, db_column="Pendencia", max_length=50, null=True
                    ),
                ),
                (
                    "modelo_sistema",
                    models.CharField(
                        blank=True, db_column="ModeloSistema", max_length=50, null=True
                    ),
                ),
                (
                    "avisar_dia",
                    models.CharField(
                        blank=True, db_column="AvisarDia", max_length=10, null=True
                    ),
                ),
                (
                    "cad_imob",
                    models.CharField(
                        blank=True, db_column="CadImob", max_length=50, null=True
                    ),
                ),
                (
                    "cmc",
                    models.CharField(
                        blank=True, db_column="CMC", max_length=50, null=True
                    ),
                ),
                (
                    "area2",
                    models.CharField(
                        blank=True, db_column="area2", max_length=50, null=True
                    ),
                ),
                (
                    "ponto_ref",
                    models.CharField(
                        blank=True, db_column="PontoRef", max_length=100, null=True
                    ),
                ),
                (
                    "sanitariocontrole1",
                    models.CharField(
                        blank=True,
                        db_column="Sanitariocontrole1",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sanitariocontrole2",
                    models.CharField(
                        blank=True,
                        db_column="Sanitariocontrole2",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sanitariocontrole3",
                    models.CharField(
                        blank=True,
                        db_column="Sanitariocontrole3",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, db_column="Observacao", null=True),
                ),
                (
                    "protocolo_tipo",
                    models.CharField(
                        blank=True, db_column="ProtocoloTipo", max_length=50, null=True
                    ),
                ),
                (
                    "protocolo_n",
                    models.CharField(
                        blank=True, db_column="ProtocoloN", max_length=50, null=True
                    ),
                ),
                (
                    "protocolo_ano",
                    models.CharField(
                        blank=True, db_column="ProtocoloAno", max_length=4, null=True
                    ),
                ),
                (
                    "protocolo_senha",
                    models.CharField(
                        blank=True, db_column="ProtocoloSenha", max_length=50, null=True
                    ),
                ),
                (
                    "historico",
                    models.TextField(blank=True, db_column="Historico", null=True),
                ),
                (
                    "bombeiro_situacao",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroSituacao",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bombeiro_provisorio_data",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroProvisorioDATA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ambiental_provisorio_data",
                    models.CharField(
                        blank=True,
                        db_column="AmbientalProvisorioDATA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "viabilidade_provisorio_data",
                    models.CharField(
                        blank=True,
                        db_column="ViabilidadeProvisorioDATA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sanitario_provisorio_data",
                    models.CharField(
                        blank=True,
                        db_column="SanitarioProvisorioDATA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "setran_provisorio_data",
                    models.CharField(
                        blank=True,
                        db_column="SetranProvisorioDATA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "orgao_rg_requerente",
                    models.CharField(
                        blank=True,
                        db_column="OrgaoRGRequerente",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "estado_orgao_rg_requerente",
                    models.CharField(
                        blank=True,
                        db_column="EstadoOrgaoRGRequerente",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numero_processo",
                    models.CharField(
                        blank=True, db_column="NumeroProcesso", max_length=50, null=True
                    ),
                ),
                (
                    "recibo_processo",
                    models.CharField(
                        blank=True, db_column="ReciboProcesso", max_length=50, null=True
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        blank=True, db_column="Prioridade", max_length=50, null=True
                    ),
                ),
                (
                    "matriz",
                    models.CharField(
                        blank=True, db_column="Matriz", max_length=50, null=True
                    ),
                ),
                (
                    "bombeiro_data_multa",
                    models.CharField(
                        blank=True,
                        db_column="BombeiroDataMulta",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nlaudo_secundario",
                    models.CharField(
                        blank=True,
                        db_column="NlaudoSecundario",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cnae_primario",
                    models.CharField(
                        blank=True, db_column="CNAEPrimario", max_length=100, null=True
                    ),
                ),
                (
                    "alvara",
                    models.CharField(
                        blank=True, db_column="Alvara", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Parcelamentos",
                "managed": False,
            },
        ),
    ]
