# Generated by Django 5.1.7 on 2025-03-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laudos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="laudo",
            table="Laudos",
        ),
    ]
