# Generated by Django 5.1.7 on 2025-04-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laudos", "0002_alter_laudo_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laudo",
            options={"managed": True},
        ),
    ]
