# Generated by Django 5.1.7 on 2025-04-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laudos", "0003_alter_laudo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laudo",
            options={"managed": False},
        ),
    ]
