# Generated by Django 5.2.2 on 2025-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0005_convert_date_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laudo',
            options={'managed': False, 'ordering': ['id_laudos']},
        ),
    ]
